name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          path: './'
          
      - name: Verify Files
        run: ls -la

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        working-directory: '../../package.json'  # Explicit working directory
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.Docker_Repo_Token }}
        run: npx semantic-release
